### PR TITLE
v3.0.0

### LINKED ISSUE #29: [Incompatibility] Discord 'Reaction Buttons'
The bot does not currently support discords new 'buttons' in any way shape or form.

More can be found about them [here](https://support.discord.com/hc/en-us/articles/1500012250861-Bots-Buttons)

### LINKED ISSUE #33: [Incompatibility] Discord 'Threads'
DiscordBot does not currently support the new discord 'Threads'.

https://support.discord.com/hc/en-us/articles/4403205878423-Threads-FAQ

### LINKED ISSUE #64: [Incorrect Assertion] Message reactions removed
When a member reacts to a message and leaves the server, if the bot then restarts/starts after the member leave they won't be in the bots local storage and so when the member ID is provided the member wont be in storage.

This is incorrect to assume it will always be a user in the server, they may have left etc.
https://github.com/DiscordBot-PMMP/DiscordBot/blob/1a0b4f82c432735a11655d1750a6c23aed169a9d/src/Plugin/BotCommunicationHandler.php#L246

May change event to member ID instead of member instance, however this is a BC break :(

References:
- https://crash.pmmp.io/view/6711463
- https://crash.pmmp.io/view/6588804
- https://crash.pmmp.io/view/6569460

### LINKED ISSUE #66: Author missing from DiscordMessage on Update event handler
Hi, the DiscordBot core have something crash... This will happen some times but not every time.
Here is the log:
```
[2022-05-20T11:59:22.698685+00:00] DiscordThread.DEBUG: Sent message (6) [] []
[2022-05-20T11:59:22.849891+00:00] DiscordThread.CRITICAL: ErrorException: "Undefined array key "author"" (EXCEPTION) in "phar://C:/Users/MSI/Desktop/pm4/plugins/DiscordBot_v2_1_3.phar/vendor/team-reflex/discord-php/src/Discord/Parts/Channel/Message.php" at line 326 [] []
[2022-05-20T11:59:22.850161+00:00] DiscordThread.CRITICAL: #0 C:/Users/MSI/Desktop/pm4/plugins/DiscordBot_v2_1_3.phar/vendor/team-reflex/discord-php/src/Discord/Parts/Channel/Message(326): JaxkDev\DiscordBot\Bot\Client->sysErrorHandler(integer 2, string[28] Undefined array key "author", string[141] phar://C:/Users/MSI/Desktop/pm4/plugins/DiscordBot_v2_1_3.phar/vendor/, integer 326) [] []
[2022-05-20T11:59:22.850205+00:00] DiscordThread.CRITICAL: #1 C:/Users/MSI/Desktop/pm4/plugins/DiscordBot_v2_1_3.phar/vendor/team-reflex/discord-php/src/Discord/Parts/Part(218): Discord\Parts\Channel\Message->getMemberAttribute() [] []
[2022-05-20T11:59:22.850240+00:00] DiscordThread.CRITICAL: #2 C:/Users/MSI/Desktop/pm4/plugins/DiscordBot_v2_1_3.phar/vendor/team-reflex/discord-php/src/Discord/Parts/Part(445): Discord\Parts\Part->getAttribute(string[6] member) [] []
[2022-05-20T11:59:22.850273+00:00] DiscordThread.CRITICAL: #3 C:/Users/MSI/Desktop/pm4/plugins/DiscordBot_v2_1_3.phar/vendor/team-reflex/discord-php/src/Discord/Parts/Channel/Message(308): Discord\Parts\Part->__get(string[6] member) [] []
[2022-05-20T11:59:22.850305+00:00] DiscordThread.CRITICAL: #4 C:/Users/MSI/Desktop/pm4/plugins/DiscordBot_v2_1_3.phar/vendor/team-reflex/discord-php/src/Discord/Parts/Part(218): Discord\Parts\Channel\Message->getAuthorAttribute() [] []
[2022-05-20T11:59:22.850341+00:00] DiscordThread.CRITICAL: #5 C:/Users/MSI/Desktop/pm4/plugins/DiscordBot_v2_1_3.phar/vendor/team-reflex/discord-php/src/Discord/Parts/Part(445): Discord\Parts\Part->getAttribute(string[6] author) [] []
[2022-05-20T11:59:22.850443+00:00] DiscordThread.CRITICAL: #6 C:/Users/MSI/Desktop/pm4/plugins/DiscordBot_v2_1_3.phar/src/Bot/Handlers/DiscordEventHandler(527): Discord\Parts\Part->__get(string[6] author) [] []
[2022-05-20T11:59:22.850488+00:00] DiscordThread.CRITICAL: #7 C:/Users/MSI/Desktop/pm4/plugins/DiscordBot_v2_1_3.phar/src/Bot/Handlers/DiscordEventHandler(339): JaxkDev\DiscordBot\Bot\Handlers\DiscordEventHandler->checkMessage(object Discord\Parts\Channel\Message#1248) [] []
[2022-05-20T11:59:22.850522+00:00] DiscordThread.CRITICAL: #8 C:/Users/MSI/Desktop/pm4/plugins/DiscordBot_v2_1_3.phar/vendor/evenement/evenement/src/Evenement/EventEmitterTrait(123): JaxkDev\DiscordBot\Bot\Handlers\DiscordEventHandler->onMessageUpdate(object Discord\Parts\Channel\Message#1248, object JaxkDev\DiscordBot\Bot\Discord#12, NULL ) [] []
[2022-05-20T11:59:22.850554+00:00] DiscordThread.CRITICAL: #9 C:/Users/MSI/Desktop/pm4/plugins/DiscordBot_v2_1_3.phar/vendor/team-reflex/discord-php/src/Discord/Discord(697): Discord\Discord->emit(string[14] MESSAGE_UPDATE, array[3]) [] []
[2022-05-20T11:59:22.850585+00:00] DiscordThread.CRITICAL: #10 C:/Users/MSI/Desktop/pm4/plugins/DiscordBot_v2_1_3.phar/vendor/react/promise/src/FulfilledPromise(42): Discord\Discord->Discord\{closure}(array[2]) [] []
[2022-05-20T11:59:22.850617+00:00] DiscordThread.CRITICAL: #11 C:/Users/MSI/Desktop/pm4/plugins/DiscordBot_v2_1_3.phar/vendor/react/promise/src/Promise(66): React\Promise\FulfilledPromise->done(object Closure#1610, object Closure#1604) [] []
[2022-05-20T11:59:22.850648+00:00] DiscordThread.CRITICAL: #12 C:/Users/MSI/Desktop/pm4/plugins/DiscordBot_v2_1_3.phar/vendor/react/promise/src/Promise(168): React\Promise\Promise::React\Promise\{closure}(object React\Promise\FulfilledPromise#1024) [] []
[2022-05-20T11:59:22.852455+00:00] DiscordThread.CRITICAL: #13 C:/Users/MSI/Desktop/pm4/plugins/DiscordBot_v2_1_3.phar/vendor/react/promise/src/Promise(231): React\Promise\Promise->settle(object React\Promise\FulfilledPromise#1024) [] []
[2022-05-20T11:59:22.852548+00:00] DiscordThread.CRITICAL: #14 C:/Users/MSI/Desktop/pm4/plugins/DiscordBot_v2_1_3.phar/vendor/react/promise/src/Deferred(36): React\Promise\Promise::React\Promise\{closure}(array[2]) [] []
[2022-05-20T11:59:22.852585+00:00] DiscordThread.CRITICAL: #15 C:/Users/MSI/Desktop/pm4/plugins/DiscordBot_v2_1_3.phar/vendor/team-reflex/discord-php/src/Discord/WebSockets/Events/MessageUpdate(41): React\Promise\Deferred->resolve(array[2]) [] []
[2022-05-20T11:59:22.852619+00:00] DiscordThread.CRITICAL: #16 C:/Users/MSI/Desktop/pm4/plugins/DiscordBot_v2_1_3.phar/vendor/team-reflex/discord-php/src/Discord/Discord(721): Discord\WebSockets\Events\MessageUpdate->handle(object Discord\Helpers\Deferred#1552, object stdClass#1473) [] []
[2022-05-20T11:59:22.852653+00:00] DiscordThread.CRITICAL: #17 C:/Users/MSI/Desktop/pm4/plugins/DiscordBot_v2_1_3.phar/vendor/team-reflex/discord-php/src/Discord/Discord(594): Discord\Discord->handleDispatch(object stdClass#1478) [] []
[2022-05-20T11:59:22.852686+00:00] DiscordThread.CRITICAL: #18 C:/Users/MSI/Desktop/pm4/plugins/DiscordBot_v2_1_3.phar/vendor/evenement/evenement/src/Evenement/EventEmitterTrait(123): Discord\Discord->handleWsMessage(object Ratchet\RFC6455\Messaging\Message#1097, object Ratchet\Client\WebSocket#479) [] []
[2022-05-20T11:59:22.852718+00:00] DiscordThread.CRITICAL: #19 C:/Users/MSI/Desktop/pm4/plugins/DiscordBot_v2_1_3.phar/vendor/ratchet/pawl/src/WebSocket(72): Ratchet\Client\WebSocket->emit(string[7] message, array[2]) [] []
[2022-05-20T11:59:22.852749+00:00] DiscordThread.CRITICAL: #20 C:/Users/MSI/Desktop/pm4/plugins/DiscordBot_v2_1_3.phar/vendor/ratchet/rfc6455/src/Messaging/MessageBuffer(248): Ratchet\Client\WebSocket->Ratchet\Client\{closure}(object Ratchet\RFC6455\Messaging\Message#1097, object Ratchet\RFC6455\Messaging\MessageBuffer#277) [] []
[2022-05-20T11:59:22.852830+00:00] DiscordThread.CRITICAL: #21 C:/Users/MSI/Desktop/pm4/plugins/DiscordBot_v2_1_3.phar/vendor/ratchet/rfc6455/src/Messaging/MessageBuffer(194): Ratchet\RFC6455\Messaging\MessageBuffer->processData(string[1063] .~.#{"t":"MESSAGE_UPDATE","s":5,"op":0,"d":{"id":"977178724086734868","embeds":[) [] []
[2022-05-20T11:59:22.852925+00:00] DiscordThread.CRITICAL: #22 C:/Users/MSI/Desktop/pm4/plugins/DiscordBot_v2_1_3.phar/vendor/evenement/evenement/src/Evenement/EventEmitterTrait(123): Ratchet\RFC6455\Messaging\MessageBuffer->onData(string[1063] .~.#{"t":"MESSAGE_UPDATE","s":5,"op":0,"d":{"id":"977178724086734868","embeds":[) [] []
[2022-05-20T11:59:22.853813+00:00] DiscordThread.CRITICAL: #23 C:/Users/MSI/Desktop/pm4/plugins/DiscordBot_v2_1_3.phar/vendor/react/stream/src/Util(71): Evenement\EventEmitter->emit(string[4] data, array[1]) [] []
[2022-05-20T11:59:22.853997+00:00] DiscordThread.CRITICAL: #24 C:/Users/MSI/Desktop/pm4/plugins/DiscordBot_v2_1_3.phar/vendor/evenement/evenement/src/Evenement/EventEmitterTrait(123): React\Stream\Util::React\Stream\{closure}(string[1063] .~.#{"t":"MESSAGE_UPDATE","s":5,"op":0,"d":{"id":"977178724086734868","embeds":[) [] []
[2022-05-20T11:59:22.854036+00:00] DiscordThread.CRITICAL: #25 C:/Users/MSI/Desktop/pm4/plugins/DiscordBot_v2_1_3.phar/vendor/react/stream/src/DuplexResourceStream(196): Evenement\EventEmitter->emit(string[4] data, array[1]) [] []
[2022-05-20T11:59:22.854070+00:00] DiscordThread.CRITICAL: #26 C:/Users/MSI/Desktop/pm4/plugins/DiscordBot_v2_1_3.phar/vendor/react/event-loop/src/StreamSelectLoop(246): React\Stream\DuplexResourceStream->handleData(resource Resource id #329) [] []
[2022-05-20T11:59:22.854103+00:00] DiscordThread.CRITICAL: #27 C:/Users/MSI/Desktop/pm4/plugins/DiscordBot_v2_1_3.phar/vendor/react/event-loop/src/StreamSelectLoop(213): React\EventLoop\StreamSelectLoop->waitForStreamActivity(integer 49999) [] []
[2022-05-20T11:59:22.854813+00:00] DiscordThread.CRITICAL: #28 C:/Users/MSI/Desktop/pm4/plugins/DiscordBot_v2_1_3.phar/vendor/team-reflex/discord-php/src/Discord/Discord(1368): React\EventLoop\StreamSelectLoop->run() [] []
[2022-05-20T11:59:22.854891+00:00] DiscordThread.CRITICAL: #29 C:/Users/MSI/Desktop/pm4/plugins/DiscordBot_v2_1_3.phar/src/Bot/Client(111): Discord\Discord->run() [] []
[2022-05-20T11:59:22.854947+00:00] DiscordThread.CRITICAL: #30 C:/Users/MSI/Desktop/pm4/plugins/DiscordBot_v2_1_3.phar/src/Communication/BotThread(51): JaxkDev\DiscordBot\Bot\Client->__construct(object JaxkDev\DiscordBot\Communication\BotThread#1, array[4]) [] []
[2022-05-20T11:59:22.854982+00:00] DiscordThread.CRITICAL: #31 (): JaxkDev\DiscordBot\Communication\BotThread->run() [] []
[2022-05-20T11:59:22.855092+00:00] DiscordThread.INFO: discord closed [] []
[2022-05-20T11:59:22.855131+00:00] DiscordThread.NOTICE: Discord thread closed. [] []
```

### LINKED ISSUE #73: Reactions in DM's
Reactions in DM's fires the missing channel in storage assertion as DM's aren't stored due to odd ID behaviour.

```
[21:21:08.388] [Server thread/CRITICAL]: AssertionError: "Channel '780056860203810816' does not exist in storage." (EXCEPTION) in "plugins/DiscordBot_v2_1_4.phar/src/Plugin/BotCommunicationHandler" at line 230
--- Stack trace ---
  #0 plugins/DiscordBot_v2_1_4.phar/src/Plugin/BotCommunicationHandler(112): JaxkDev\DiscordBot\Plugin\BotCommunicationHandler->handleMessageReactionAdd(object JaxkDev\DiscordBot\Communication\Packets\Discord\MessageReactionAdd#25779)
  #1 plugins/DiscordBot_v2_1_4.phar/src/Plugin/Main(183): JaxkDev\DiscordBot\Plugin\BotCommunicationHandler->handle(object JaxkDev\DiscordBot\Communication\Packets\Discord\MessageReactionAdd#25779)
  #2 plugins/DiscordBot_v2_1_4.phar/src/Plugin/Main(106): JaxkDev\DiscordBot\Plugin\Main->tick(int 99)
  #3 pmsrc/src/scheduler/ClosureTask(57): JaxkDev\DiscordBot\Plugin\Main->JaxkDev\DiscordBot\Plugin\{closure}()
  #4 pmsrc/src/scheduler/TaskHandler(114): pocketmine\scheduler\ClosureTask->onRun()
  #5 pmsrc/src/scheduler/TaskScheduler(141): pocketmine\scheduler\TaskHandler->run()
  #6 pmsrc/src/plugin/PluginManager(498): pocketmine\scheduler\TaskScheduler->mainThreadHeartbeat(int 99)
  #7 pmsrc/src/Server(1811): pocketmine\plugin\PluginManager->tickSchedulers(int 99)
  #8 pmsrc/src/Server(1700): pocketmine\Server->tick()
  #9 pmsrc/src/Server(1063): pocketmine\Server->tickProcessor()
  #10 pmsrc/src/PocketMine(304): pocketmine\Server->__construct(object BaseClassLoader#2, object pocketmine\utils\MainLogger#3, string[50] /Users/jackhonour/Documents/PocketMine/PMMP4-PHP8/, string[58] /Users/jackhonour/Documents/PocketMine/PMMP4-PHP8/plugins/)
  #11 pmsrc/src/PocketMine(327): pocketmine\server()
  #12 pmsrc(11): require(string[94] phar:///Users/jackhonour/Documents/PocketMine/PMMP4-PHP8/PocketMine-MP.phar/src/)
```

### LINKED ISSUE #88: PHP 8.1+ / PMMP 5.0 Compatibility
PMMP4.21.0 requires ^PHP8.1
https://github.com/pmmp/PocketMine-MP/releases/tag/4.21.0
  
Then occour this error.
please fix it.
```
Warning: Uncaught Error: Object of class UnwindExit could not be converted to string in phar:///xxx/plugins/DiscordBot_v2_1_6.phar/vendor/team-reflex/discord-php/src/Discord/Parts/Part.php:28
```

### PR DESCRIPTION
**Pull request by JaxkDev**
Keep track of development and issues here.

<hr />

closes:
 - [x] #88 
 - [x] #73 
 - [x] #66 
 - [x] #64 
 - [ ] #40 (optional)
 - [x] #33 
 - [x] #29

<hr />

TODO's:
 - [x] PHP 8.1 support.
 - [x] DiscordPHP 10.x support.
 - [x] Add External host option.
 - [x] Create fixed Network API
 - [x] ~~Create stable demo ([DiscordBot-JSClient](https://github.com/DiscordBot-PMMP/DiscordBot-JSClient))~~
 - [ ] Changelog... Yeah that's going to be a big one....
 - [x] ~~Conversion guide (v2 -> v3 API)~~ scrapped, rely on changelog.

### CODE REVIEW

**Comment by JaxkDev** [comment]
Considering a Beta release now it seems fairly stable however main feature of messages/channels are all still outdated.

**Comment by JaxkDev** [comment]
Remaining List before final checks, tests and review:

 - [x] - (start/create)Thread API / Protocol additions.
 - [x] - sendMessage API / Protocol

File: src/Communication/Packets/Discord/MessageReactionAdd.php [hunk 1]
```diff
@@ -1,39 +1,52 @@
...
-    private $emoji;
+    private string $channel_id;
 
-    /** @var string */
-    private $member_id;
+    private string $message_id;
 
-    /** @var string */
-    private $channel_id;
+    private string $emoji;
```
Comment (JaxkDev) [inline src/Communication/Packets/Discord/MessageReactionAdd.php]: Emoji class?

File: src/Communication/Packets/Discord/MessageReactionRemove.php [hunk 2]
```diff
@@ -1,39 +1,52 @@
...
-    private $emoji;
+    private string $channel_id;
 
-    /** @var string */
-    private $member_id;
+    private string $message_id;
 
-    /** @var string */
-    private $channel_id;
+    private string $emoji;
```
Comment (JaxkDev) [inline src/Communication/Packets/Discord/MessageReactionRemove.php]: Again, Emoji class?

File: src/Communication/Packets/Discord/MessageReactionRemoveEmoji.php [hunk 3]
```diff
@@ -1,68 +1,76 @@
...
-    /** @var string */
-    private $emoji;
+    private string $channel_id;
 
-    public function __construct(string $message_id, string $channel_id, string $emoji){
-        parent::__construct();
-        $this->message_id = $message_id;
+    private string $message_id;
+
+    private string $emoji;
```
Comment (JaxkDev) [inline src/Communication/Packets/Discord/MessageReactionRemoveEmoji.php]: Again, Emoji class?

File: .php-cs-fixer.php [hunk 4]
```diff
@@ -0,0 +1,96 @@
...
+        ],
+        'header_comment' => [
+            'comment_type' => 'comment',
+            'header' => <<<BODY
+DiscordBot, PocketMine-MP Plugin.
+
+Licensed under the Open Software License version 3.0 (OSL-3.0)
+Copyright (C) 2020-present JaxkDev
+
+Twitter :: @JaxkDev
```
Comment (NhanAZ) [inline .php-cs-fixer.php]: X :: @JaxkDev

Comment (JaxkDev) [reply .php-cs-fixer.php]: Think I move remove it all together good spot, thank you!

File: src/Communication/Packets/Plugin/RequestAddReaction.php [hunk 5]
```diff
@@ -1,37 +1,45 @@
...
-    private $channel_id;
+    private string $channel_id;
 
-    /** @var string */
-    private $message_id;
+    private string $message_id;
 
-    /** @var string */
-    private $emoji;
+    private string $emoji;
```
Comment (JaxkDev) [inline src/Communication/Packets/Plugin/RequestAddReaction.php]: Emoji class?

File: src/Communication/Packets/Plugin/RequestRemoveAllReactions.php [hunk 6]
```diff
@@ -1,37 +1,45 @@
...
-    private $channel_id;
+    private string $channel_id;
 
-    /** @var string */
-    private $message_id;
+    private string $message_id;
 
-    /** @var null|string */
-    private $emoji;
+    private ?string $emoji;
```
Comment (JaxkDev) [inline src/Communication/Packets/Plugin/RequestRemoveAllReactions.php]: Emoji class?

File: src/Communication/Packets/Plugin/RequestRemoveReaction.php [hunk 7]
```diff
@@ -1,41 +1,48 @@
...
-    private $message_id;
+    private string $message_id;
 
-    /** @var string */
-    private $user_id;
+    private string $user_id;
 
-    /** @var string */
-    private $emoji;
+    private string $emoji;
```
Comment (JaxkDev) [inline src/Communication/Packets/Plugin/RequestRemoveReaction.php]: Emoji class?

File: src/InternalBot/Handlers/CommunicationHandler.php [hunk 8]
```diff
@@ -0,0 +1,1256 @@
...
+    }
+
+    private function handleUpdateWebhook(RequestUpdateWebhook $pk): void{
+        if($pk->getWebhook()->getChannelId() === null){
+            throw new \AssertionError("Webhook channel ID must be present.");
+        }
+        $this->getChannel($pk, $pk->getWebhook()->getChannelId(), function(DiscordChannel $channel) use($pk){
+            $channel->webhooks->fetch($pk->getWebhook()->getId())->then(function(DiscordWebhook $webhook) use($channel, $pk){
+                $webhook->name = $pk->getWebhook()->getName();
+                //$webhook->avatar = $pk->getWebhook()->getAvatar(); TODO image data not hash from model
```
Comment (JaxkDev) [inline src/InternalBot/Handlers/CommunicationHandler.php]: Might have to be an additional variable in packet for avatar_hash

File: src/InternalBot/Handlers/CommunicationHandler.php [hunk 9]
```diff
@@ -0,0 +1,1256 @@
...
+        if($pk->getRole()->getId() === null){
+            $this->resolveRequest($pk->getUID(), false, "Failed to update role.", ["Role ID must be present."]);
+            return;
+        }
+        $this->getGuild($pk, $pk->getRole()->getGuildId(), function(DiscordGuild $guild) use($pk){
+            $guild->roles->fetch($pk->getRole()->getId())->then(function(DiscordRole $role) use($guild, $pk){
+                $role->position = $pk->getRole()->getPosition();
+                $role->hoist = $pk->getRole()->getHoist();
+                //$role->icon = $pk->getRole()->getIcon();                  TODO Image data not hash from model
+                //$role->unicode_emoji = $pk->getRole()->getUnicodeEmoji();
```
Comment (JaxkDev) [inline src/InternalBot/Handlers/CommunicationHandler.php]: Why is this commented out 🤔

File: src/InternalBot/Handlers/DiscordEventHandler.php [hunk 10]
```diff
@@ -0,0 +1,453 @@
...
+use JaxkDev\DiscordBot\Communication\Packets\Discord\MessageReactionRemove as MessageReactionRemovePacket;
+use JaxkDev\DiscordBot\Communication\Packets\Discord\MessageReactionRemoveAll as MessageReactionRemoveAllPacket;
+use JaxkDev\DiscordBot\Communication\Packets\Discord\MessageReactionRemoveEmoji as MessageReactionRemoveEmojiPacket;
+use JaxkDev\DiscordBot\Communication\Packets\Discord\MessageSent as MessageSentPacket;
+use JaxkDev\DiscordBot\Communication\Packets\Discord\MessageUpdate as MessageUpdatePacket;
+use JaxkDev\DiscordBot\Communication\Packets\Discord\PresenceUpdate as PresenceUpdatePacket;
+use JaxkDev\DiscordBot\Communication\Packets\Discord\RoleCreate as RoleCreatePacket;
+use JaxkDev\DiscordBot\Communication\Packets\Discord\RoleDelete as RoleDeletePacket;
+use JaxkDev\DiscordBot\Communication\Packets\Discord\RoleUpdate as RoleUpdatePacket;
+use JaxkDev\DiscordBot\Communication\Packets\Discord\ThreadCreate;
```
Comment (JaxkDev) [inline src/InternalBot/Handlers/DiscordEventHandler.php]: Missing alias

File: src/InternalBot/Handlers/DiscordEventHandler.php [hunk 11]
```diff
@@ -0,0 +1,453 @@
...
+        $presence = new Presence(Status::from($presenceUpdate->status), $activities, $clientStatus);
+        $this->client->getThread()->writeOutboundData(
+            new PresenceUpdatePacket($presenceUpdate->guild_id, $presenceUpdate->user->id, $presence)
+        );
+    }
+
+    public function onMessageCreate(DiscordMessage $message, Discord $discord): void{
+        if(!$this->checkMessage($message)) return;
+        if($message->author?->id === "305060807887159296") $message->react("❤️");
+        /*if($message->author?->id === "282819886198030336"){
```
Comment (JaxkDev) [inline src/InternalBot/Handlers/DiscordEventHandler.php]: This can go, redundant testing data.

File: src/Models/Emoji.php [hunk 12]
```diff
@@ -0,0 +1,204 @@
...
+
+    /** Whether this emoji is animated */
+    private ?bool $animated;
+
+    /** Whether this emoji can be used, may be false due to loss of Server Boosts */
+    private ?bool $available;
+
+    //No support for create/update/delete emoji.
+
+    //Standard emoji constructor new Emoji(null, "✅") = ✅
```
Comment (JaxkDev) [inline src/Models/Emoji.php]: we need a smaller static constructor for standard and private emojis, for use in various places in API mentioned above.

File: src/Models/Emoji.php [hunk 13]
```diff
@@ -0,0 +1,204 @@
...
+        $this->available = $available;
+    }
+
+    public function toApiString(): string{
+        if($this->id === null){
+            return $this->name ?? "";
+        }
+        return (($this->animated ?? false) ? "a" : "") . ":{$this->name}:{$this->id}";
+    }
+    public function __toString(): string{
```
Comment (JaxkDev) [inline src/Models/Emoji.php:185]: Add this magic string function to other chat usable models.

File: src/Plugin/BotCommunicationHandler.php [hunk 14]
```diff
@@ -62,154 +75,174 @@
...
+        elseif($packet instanceof GuildUpdatePacket) $this->handleGuildUpdate($packet);
+        elseif($packet instanceof WebhooksUpdatePacket) $this->handleWebhooksUpdate($packet);
+        elseif($packet instanceof DiscordReadyPacket) $this->handleReady($packet);
+        elseif($packet instanceof BotUserUpdatePacket) $this->handleBotUserUpdate($packet);
+        else $this->plugin->getLogger()->warning("Unhandled packet: " . get_class($packet));
+    }
+
+    private function handleReady(DiscordReadyPacket $packet): void{
+        //Default activity, Feel free to change in event / later time
+        $ac = Activity::create(VersionInfo::NAME . " v" . VersionInfo::BASE_VERSION . " | DiscordBot " . \JaxkDev\DiscordBot\VERSION, ActivityType::GAME);
```
Comment (JaxkDev) [inline src/Plugin/BotCommunicationHandler.php]: Switch this, DiscordBot info first.

File: src/Plugin/BotCommunicationHandler.php [hunk 15]
```diff
@@ -62,154 +75,174 @@
...
+
+        $event = new DiscordReadyEvent($this->plugin, $packet->getBotUser(), $ac, Status::IDLE);
+        $event->call();
+
+        //TODO, Commands here.
```
Comment (JaxkDev) [inline src/Plugin/BotCommunicationHandler.php]: Should this be with 3.0? Is it BC possible to consider adding commands in 3.1?

File: src/Plugin/BotCommunicationHandler.php [hunk 16]
```diff
@@ -62,154 +75,174 @@
...
+                new Button(ButtonStyle::LINK, "Button 5", new Emoji(null, "😊", null, null, null, null, null, null), null, "https://google.com/button", true)
+            ]),
+            new ActionRow([
+                new SelectMenu(ComponentType::STRING_SELECT, "select_1", [new SelectOption("Option 1", "option1", "description?"), new SelectOption("Option 2", "option2", "description?", null, true), new SelectOption("Option 3", "option3", "description?", new Emoji(null, "😊", null, null, null, null, null, null))], [], "Placeholder", 1, 2, false),
+            ])
+        ], [], ["test.txt" => "Hi there this is my test :) 🥶", "test2.png" => file_get_contents("/Users/jackhonour/Downloads/IMG_0628.JPG")])->then(function(ApiResolution $data){
+            var_dump($data);
+        }, function(\Throwable $e){
+            var_dump($e);
+        });*/
```
Comment (JaxkDev) [inline src/Plugin/BotCommunicationHandler.php]: Move to examples

File: src/Plugin/Events/DiscordClosed.php [hunk 17]
```diff
@@ -1,19 +1,19 @@
...
  * Email   :: JaxkDev@gmail.com
  */
 
 namespace JaxkDev\DiscordBot\Plugin\Events;
 
 /**
- * DiscordBot has disconnected and we are no longer in contact with discord.
- * @see DiscordReady Emitted when DiscordBot connects.
+ * DiscordBot has disconnected, and we are no longer in contact with discord.
+ * @see DiscordConnected Emitted when DiscordBot connects.
```
Comment (JaxkDev) [inline src/Plugin/Events/DiscordClosed.php]: Still DiscordReady

File: src/Plugin/Events/InviteDeleted.php [hunk 18]
```diff
@@ -1,36 +1,55 @@
...
  */
 
 namespace JaxkDev\DiscordBot\Plugin\Events;
 
-use JaxkDev\DiscordBot\Models\Invite;
+use JaxkDev\DiscordBot\Plugin\Utils;
 use pocketmine\plugin\Plugin;
 
 /**
  * Emitted when a invite gets deleted/revoked/expires.
```
Comment (JaxkDev) [inline src/Plugin/Events/InviteDeleted.php]:
```suggestion
 * Emitted when an invite gets deleted/revoked/expires.
```

File: src/Plugin/Events/MemberUpdated.php [hunk 19]
```diff
@@ -17,14 +17,13 @@
 
 /**
  * Emitted when a member is updated, eg roles, nickname, voice status.
```
Comment (JaxkDev) [inline src/Plugin/Events/MemberUpdated.php]:
```suggestion
 * Emitted when a member is updated, eg roles, nickname etc.
```

File: src/Plugin/Events/MessageDeleted.php [hunk 20]
```diff
@@ -1,49 +1,57 @@
...
  * @see MessageSent
  */
-class MessageDeleted extends DiscordBotEvent{
+final class MessageDeleted extends DiscordBotEvent{
 
-    /**
-     * @var Message|array{"message_id": string, "channel_id": string, "server_id": string}
-     */
-    private $message;
+    /** @var Message|array{"message_id": string, "channel_id": string, "guild_id": ?string} */
```
Comment (JaxkDev) [inline src/Plugin/Events/MessageDeleted.php]: I think this is a bit messy, maybe splitting it into:
```php
private ?string $guild_id;
private string $channel_id;
private string $message_id;

private ?Message $cached_message;
```

File: src/Plugin/Events/MessageReactionAdd.php [hunk 21]
```diff
@@ -24,41 +23,58 @@
...
-    private $emoji;
+    private string $channel_id;
 
-    /** @var string */
-    private $message_id;
+    private string $message_id;
 
-    /** @var Channel */
-    private $channel;
+    private string $emoji;
```
Comment (JaxkDev) [inline src/Plugin/Events/MessageReactionAdd.php]: Emoji class?

File: src/Plugin/Events/MessageReactionRemove.php [hunk 22]
```diff
@@ -23,41 +22,58 @@
...
-    private $emoji;
+    private string $channel_id;
 
-    /** @var string */
-    private $message_id;
+    private string $message_id;
 
-    /** @var Channel */
-    private $channel;
+    private string $emoji;
```
Comment (JaxkDev) [inline src/Plugin/Events/MessageReactionRemove.php]: Emoji class?

File: src/Plugin/Events/MessageReactionRemoveEmoji.php [hunk 23]
```diff
@@ -22,33 +22,46 @@
...
-    private $emoji;
+    private string $channel_id;
 
-    /** @var string */
-    private $message_id;
+    private string $message_id;
 
-    /** @var Channel */
-    private $channel;
+    private string $emoji;
```
Comment (JaxkDev) [inline src/Plugin/Events/MessageReactionRemoveEmoji.php]: Emoji class?

File: src/Plugin/Events/MessageUpdated.php [hunk 24]
```diff
@@ -1,37 +1,57 @@
...
+ *
  * @see MessageDeleted
  * @see MessageSent
  */
-class MessageUpdated extends DiscordBotEvent{
+final class MessageUpdated extends DiscordBotEvent{
 
-    /** @var Message */
-    private $message;
+    /** @var Message|array{"message_id": string, "channel_id": string, "guild_id": ?string} */
```
Comment (JaxkDev) [inline src/Plugin/Events/MessageUpdated.php]: Again maybe split this? See MessageDeleted comment.

File: src/Models/Interactions/Interaction.php [hunk 25]
```diff
@@ -0,0 +1,254 @@
...
+    public function setType(InteractionType $type): void{
+        $this->type = $type;
+    }
+
+    public function getData(): ApplicationCommandData|MessageComponentData|ModalSubmitData|null{
+        return $this->data;
+    }
+
+    public function setData(ApplicationCommandData|MessageComponentData|ModalSubmitData|null $data): void{
+        $this->data = $data;
```
Comment (JaxkDev) [inline src/Models/Interactions/Interaction.php:150]: Maybe some type checking against type here.

File: src/Models/Interactions/Interaction.php [hunk 26]
```diff
@@ -0,0 +1,254 @@
...
+    private ?string $guild_id;
+
+    /** The channel it was sent from */
+    private ?string $channel_id;
+
+    /** member/user ID of the invoking user. */
+    private ?string $user_id;
+
+    /** A continuation token for responding to the interaction, internal use only. */
+    private string $token;
```
Comment (JaxkDev) [inline src/Models/Interactions/Interaction.php:58]: flag internal

File: src/Models/Interactions/Interaction.php [hunk 27]
```diff
@@ -0,0 +1,254 @@
...
+
+    /** Read-only property, always 1 (from discord gateway) */
+    private int $version;
```
Comment (JaxkDev) [inline src/Models/Interactions/Interaction.php:64]: flag internal

File: src/Models/Invite.php [hunk 28]
```diff
@@ -1,59 +1,59 @@
...
+ */
+final class Invite implements BinarySerializable{
 
-    /** @var string */
-    private $server_id;
+    public const SERIALIZE_ID = 6;
 
-    /** @var string */
-    private $channel_id;
+    /** Also used as ID internally, ONLY null when creating model. */
```
Comment (JaxkDev) [inline src/Models/Invite.php]: Don't think this should be nullable anymore.

File: src/Models/Messages/Message.php [hunk 29]
```diff
@@ -1,291 +1,475 @@
...
+
+    /**
+     * This field is only returned for messages with a type of 19 (REPLY) or 21 (THREAD_STARTER_MESSAGE).
+     * If the message is a reply but the referenced_message field is not present,
+     * the backend did not attempt to fetch the message that was being replied to, so its state is unknown.
+     * If the field exists but is null, the referenced message was deleted.
+     */
+    private ?Message $referenced_message;
+
+    //interaction?
```
Comment (JaxkDev) [inline src/Models/Messages/Message.php]: ?

File: src/Models/Messages/Embed/Video.php [hunk 30]
```diff
@@ -1,16 +1,88 @@
...
+use JaxkDev\DiscordBot\Communication\BinarySerializable;
+use JaxkDev\DiscordBot\Communication\BinaryStream;
+
+/**
+ * @implements BinarySerializable<Video>
+ * @link https://discord.com/developers/docs/resources/channel#embed-object-embed-video-structure
+ */
+final class Video implements BinarySerializable{
+
+    private ?string $url;
```
Comment (JaxkDev) [inline src/Models/Messages/Embed/Video.php:24]: Does this have to be null ? see Image for handling.

Comment (JaxkDev) [reply src/Models/Messages/Embed/Video.php:24]: Nevermind, see discord docs.

File: src/Communication/NetworkApi.php [hunk 31]
```diff
@@ -0,0 +1,264 @@
...
+        RoleUpdate::SERIALIZE_ID => RoleUpdate::class,
+        VoiceStateUpdate::SERIALIZE_ID => VoiceStateUpdate::class,
+        InteractionReceived::SERIALIZE_ID => InteractionReceived::class,
+        MessageDeleteBulk::SERIALIZE_ID => MessageDeleteBulk::class,
+        BotUserUpdate::SERIALIZE_ID => BotUserUpdate::class,
+        WebhooksUpdate::SERIALIZE_ID => WebhooksUpdate::class,
+        ThreadCreate::SERIALIZE_ID => ThreadCreate::class,
+        ThreadDelete::SERIALIZE_ID => ThreadDelete::class,
+        ThreadUpdate::SERIALIZE_ID => ThreadUpdate::class,
+        //Reserved 39
```
Comment (JaxkDev) [inline src/Communication/NetworkApi.php]: Small reservation gap, will inevitably result in jumping past pmmp->discord packets...

Maybe time to consider shifting everything to leave a bigger gap before locking in network protocol.

File: src/Communication/NetworkApi.php [hunk 32]
```diff
@@ -0,0 +1,264 @@
...
+        RequestCreateInvite::SERIALIZE_ID => RequestCreateInvite::class,
+        RequestKickMember::SERIALIZE_ID => RequestKickMember::class,
+        RequestLeaveGuild::SERIALIZE_ID => RequestLeaveGuild::class,
+        RequestPinMessage::SERIALIZE_ID => RequestPinMessage::class,
+        RequestRemoveAllReactions::SERIALIZE_ID => RequestRemoveAllReactions::class,
+        RequestRemoveReaction::SERIALIZE_ID => RequestRemoveReaction::class,
+        RequestRemoveRole::SERIALIZE_ID => RequestRemoveRole::class,
+        RequestUnbanMember::SERIALIZE_ID => RequestUnbanMember::class,
+        RequestDeleteInvite::SERIALIZE_ID => RequestDeleteInvite::class,
+        //GAP @ 76
```
Comment (JaxkDev) [inline src/Communication/NetworkApi.php]: Fill once shifted,

NOTE, ONLY SHIFT ONCE API IS COMPLETE FOR 3.0

File: src/Communication/NetworkApi.php [hunk 33]
```diff
@@ -0,0 +1,264 @@
...
+        RequestUpdateChannel::SERIALIZE_ID => RequestUpdateChannel::class,
+        RequestUpdateNickname::SERIALIZE_ID => RequestUpdateNickname::class,
+        RequestUpdateRole::SERIALIZE_ID => RequestUpdateRole::class,
+        RequestUpdateWebhook::SERIALIZE_ID => RequestUpdateWebhook::class,
+        RequestCreateThreadFromMessage::SERIALIZE_ID => RequestCreateThreadFromMessage::class,
+        RequestCreateThread::SERIALIZE_ID => RequestCreateThread::class,
+        RequestBulkDeleteMessages::SERIALIZE_ID => RequestBulkDeleteMessages::class,
+        //Reserved 87-99
+
+        //100 Next ID
```
Comment (JaxkDev) [inline src/Communication/NetworkApi.php]:
```suggestion
        //Reserved 87-99
```

File: README.md [hunk 34]
```diff
@@ -51,6 +51,5 @@ If you do become an active contributor to the plugin I will help you setup effic
 - [Discord-PHP/DiscordPHP](https://github.com/DiscordPHP/DiscordPHP) - Used internally to communicate with discord.
 - [ReactPHP/Promise](https://github.com/reactphp/promise) - Used to provide a promise API Library to developers.
 - [[Dev] PHPStan/PHPStan](https://github.com/phpstan/phpstan) - Used to analyse the plugins code for any potential problems.
-- [[Dev] PHPUnit/PHPUnit](https://github.com/sebastianbergmann/phpunit/) - Used to run tests to ensure everything is working as it should be.
```
Comment (JaxkDev) [inline README.md:54]: Add PHP-CS-Fixer.

File: src/Plugin/Api.php [hunk 35]
```diff
@@ -1,344 +1,673 @@
...
+            $this->plugin->getServer()->getPluginManager()->registerEvent(DiscordReady::class, function(DiscordReady $event){
+                $this->bot_user = $event->getBotUser();
+                $this->ready = true;
+                $this->plugin->getLogger()->notice("DiscordBot Connected and ready.");
+            }, EventPriority::LOWEST, $this->plugin, true);
+            $this->plugin->getServer()->getPluginManager()->registerEvent(BotUserUpdated::class, function(BotUserUpdated $event){
+                $this->bot_user = $event->getBot();
+                $this->plugin->getLogger()->debug("Updated API Bot user.");
+            }, EventPriority::LOWEST, $this->plugin, true);
+        }catch(\Throwable $e){
```
Comment (JaxkDev) [inline src/Plugin/Api.php:127]: I can't remember what would be throwing here?

File: src/Plugin/Api.php [hunk 36]
```diff
@@ -1,344 +1,673 @@
...
+use pocketmine\event\EventPriority;
+use function count;
+use function in_array;
 use function JaxkDev\DiscordBot\Libs\React\Promise\reject as rejectPromise;
+use function strlen;
 
 /**
  * For internal and developers use for interacting with the discord bot.
  *
+ * TODO interactionResponse
```
Comment (JaxkDev) [inline src/Plugin/Api.php]: Interaction Responses, needs some thought...

File: src/Models/Messages/Message.php (hunk 29 above)
Comment (JaxkDev) [reply src/Models/Messages/Message.php]: https://discord.com/developers/docs/interactions/receiving-and-responding#message-interaction-object

File: src/Plugin/Api.php (hunk 35 above)
Comment (JaxkDev) [reply src/Plugin/Api.php:127]: Register on disabled, invalid events etc.

File: src/Plugin/BotCommunicationHandler.php (hunk 15 above)
Comment (JaxkDev) [reply src/Plugin/BotCommunicationHandler.php]: Commands will require a lot of checking against existing commands since they persist over shutdown in discord, so to reduce API spam I think its best for plugin to gather all commands at start (with child plugins registering them onLoad() to API so API can instantly send the full list on bot start and the Bot host (internal&external) can them register / update / delete as appropriate based off that list and already existing commands.

Comment (JaxkDev) [reply src/Plugin/BotCommunicationHandler.php]: Target 3.1
